GET http://localhost:8080/api/sensors

###

GET http://localhost:8080/api/sensors?name=dev

###

POST http://localhost:8080/api/sensors
Content-Type: application/json

{
    "sid": "dev",
    "data": "0000000000"
}

###

DELETE  http://localhost:8080/api/sensors/632be359f5fd78bc1a8f0c9c

###

DELETE  http://localhost:8080/api/sensors