GET http://localhost:8080/api/sensors

###

GET http://localhost:8080/api/sensors?name=dev

###

POST http://localhost:8080/api/sensors
Content-Type: application/json

{
    "sid": "dev",
    "data": "0000000000"
}

###

DELETE  http://localhost:8080/api/sensors/632748fad70ef4ca91e3e8b1